from playwright.sync_api import sync_playwright
import re, time

BASE = "https://www.builtinaustin.com/jobs/product"
PAGES = 1

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36")

# Pair each job with the company link right before it (reliable, never blocked).
LIST_JS = r"""
() => {
  const nodes = Array.from(document.querySelectorAll('a[href*="/company/"], h2 a[href*="/job/"]'));
  const out = [];
  let lastCompany = "";
  nodes.forEach(el => {
    if (el.href.includes('/company/')) {
      const t = el.textContent.trim();
      if (t) lastCompany = t;
    } else {
      let card = el;
      for (let i = 0; i < 10 && card.parentElement; i++) {
        card = card.parentElement;
        if (card.textContent && card.textContent.includes('Austin')) break;
      }
      out.push({ title: el.textContent.trim(), url: el.href, company: lastCompany,
                 text: card.textContent.replace(/\s+/g,' ').trim() });
    }
  });
  return out;
}
"""

DETAIL_JS = "() => document.body.innerText"
START = "generated by AI"
ENDS = ["Read Full Description", "Similar Jobs", "What you need to know about", "Apply Instructions"]
BLOCKED = ["just a moment", "verify you are human", "verifying you are human",
           "enable javascript and cookies", "attention required",
           "needs to review the security", "cloudflare", "ray id"]

def extract_desc(body):
    i = body.find(START)
    text = body[i + len(START):] if i != -1 else body
    cut = len(text)
    for e in ENDS:
        k = text.find(e)
        if k != -1: cut = min(cut, k)
    return text[:cut].strip()[:4000]

def get_builtin_jobs(pages=PAGES):
    jobs, seen, listings = [], set(), []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(user_agent=UA, viewport={"width": 1280, "height": 900})
        page = context.new_page()
        for n in range(1, pages + 1):
            url = BASE if n == 1 else f"{BASE}?page={n}"
            print(f"Reading listing page {n}...")
            page.goto(url, timeout=60000, wait_until="domcontentloaded")
            page.wait_for_timeout(4000)
            for j in page.evaluate(LIST_JS):
                link = j["url"].split("?")[0]
                if link in seen: continue
                seen.add(link)
                listings.append(j | {"url": link})
        for idx, j in enumerate(listings, 1):
            print(f"  ({idx}/{len(listings)}) {j['title'][:45]}")
            desc = ""
            try:
                page.goto(j["url"], timeout=60000, wait_until="domcontentloaded")
                page.wait_for_timeout(2500)
                body = page.evaluate(DETAIL_JS)
                if not any(b in body.lower() for b in BLOCKED):
                    desc = extract_desc(body)
            except Exception as e:
                print(f"     (skipped: {e})")
            if len(desc) < 120 or any(b in desc.lower() for b in BLOCKED):
                desc = j["text"][:1500]
            m = re.search(r"(\d{2,3})K-(\d{2,3})K", j["text"])
            jobs.append({
                "title": j["title"],
                "company": j["company"] or "Built In (Austin)",
                "location": "Austin, TX",
                "salary_min": int(m.group(1)) * 1000 if m else None,
                "salary_max": int(m.group(2)) * 1000 if m else None,
                "description": desc, "url": j["url"],
            })
            time.sleep(1)
        browser.close()
    return jobs

if __name__ == "__main__":
    found = get_builtin_jobs()
    print(f"\nFound {len(found)} Built In Austin PM jobs\n")
    for j in found[:12]:
        sal = f"${j['salary_min']:,}-${j['salary_max']:,}" if j['salary_min'] else "salary n/a"
        print(f"- {j['title']} @ {j['company']}  ({sal}) [{len(j['description'])} chars]")